### ISSUE TITLE
[bug] staticman throws error 429

### ISSUE THREAD

**Issue by VincentTam** [hajekj/hajekj.github.io#110]
Steps to reproduce:

1. Go to https://hajekj.net/2020/04/15/staticman-setup-in-app-service/
2. Leave a comment
3. Click submit
4. Receive an error.

Analysis:

![error 429 thrown by your Staticman instance](https://user-images.githubusercontent.com/5748535/106465269-082f7080-649a-11eb-81ea-13ab8f5ea835.png)  
screenshot of web dev tool of a modern browser displaying the 429 "too many requests" error received

Tech info:

The above screenshot is taken using Opera Version:71.0.3770.198 on Ubuntu 20.04.  However, I think that that's irrelevant to the problem because this is a server-side problem reproducible in any client.

**Comment by hajekj** [comment]
Hey, thanks for letting me know. It could be related to: https://github.com/eduardoboucas/staticman/issues/222

I am actually considering replacing staticman with https://utteranc.es/ or something similar for comments. I think resubmitting the comment eventually ends up with success. I will see if I can remove the 429 protection, since I run the comments through antispam filter and captcha is there anyways.

**Comment by VincentTam** [comment]
Perhaps it's due to the lack of Akismet.  ReCAPTCHA isn't enough to stop the spam requests.

**Comment by hajekj** [comment]
I have Akismet enabled in my instance. And I just checked the monitoring and it doesn't seem to show and high request rates for past 30 days:

![image](https://user-images.githubusercontent.com/8337913/106734025-db529900-6612-11eb-9027-321d3d0f467a.png)

Definitely bots are hitting it though. I will remove the 429 protection, I think it should have no bad effect. Will see about it after some time.
